### ISSUE TITLE
Update to 1.16?

### ISSUE THREAD

**Issue by ZacBrownBand** [mixxen/cesiumjs#12]

**Comment by maikuru** [comment]
I'll get to it this weekend.

**Comment by jaga15** [comment]
Thanks

**Comment by ZacBrownBand** [comment]
Seeing as this was not updated last weekend, I found an alternative. If others are in this boat https://github.com/solarpatrol/cesium-bower

**Comment by smills2929** [comment]
What's going on?

**Comment by mixxen** [comment]
2a162ac
