### ISSUE TITLE
Can't use cesiumjs  through Asynchronous Module Definition mechanism

### ISSUE THREAD

**Issue by vrutsky** [mixxen/cesiumjs#6]
I installed this repository using ``bower install cesiumjs`` and can't use AMD to load Cesium.

I'm using Dojo toolkit like this:

    require([
      'dojo/dom',
      'dojo/parser',
      'cesiumjs/Cesium/Cesium',
      'dojo/domReady!'
    ], function (dom, parser, Cesium) {
      parser.parse();

      // outputs "not-a-module"
      console.log(Cesium)
    }

**Comment by maikuru** [comment]
I've never used Dojos AMD, but I would  make sure it's pointing to the actual Cesium.js file and not the directory 


Cheers,-Mike




—————————

Michael Lodge-Paolini

Myflipside Media, LLC

mlodgepaolini@myflipsidemedia.com

**Comment by vrutsky** [comment]
Looks like default CesiumJS build can't be used with RequireJS [1]:

    The combined Cesium.js produced by the build file is designed for standalone use (to be loaded
    from a script tag), and not with RequireJS.  To use RequireJS, you can download the full Cesium
    zip file (or clone from GitHub and run the build), and copy the contents of the Source directory
    into your libs/Cesium directory instead.  You can then either require in the Cesium module as you
    are currently, which will in turn load all the Cesium modules, or you can require in each module
    individually that you want to use, which gives you control over how much code gets loaded by
    your application.

So this bug report is invalid.

[1] https://groups.google.com/d/msg/cesium-dev/c5O7Oar4Chc/44vHIoVvUP4J
